### PR TITLE
Include CAPI repo to the list of cloned repos

### PR DESCRIPTION
**Pull request by Xenwar**
Include CAPI repo to the list of cloned repos. required in Tilt based environment setup.

### CODE REVIEW

**Review by namnx228 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
@Xenwar just a suggestion: I think we can just revert https://github.com/metal3-io/metal3-dev-env/pull/533 it is more cleaner IMO and this is what you are trying to achieve here, WDYT?

**Comment by Xenwar** [comment]
> @Xenwar just a suggestion: I think we can just revert #533 it is more cleaner IMO and this is what you are trying to achieve here, WDYT?

Thanks. That is exactly what I am trying to achieve.

**Comment by Xenwar** [comment]
update pr with content of #533. Not sure if there are better ways of achieving that.

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
cc @namnx228

**Comment by kashifest** [comment]
Shall we clone CAPI all the time or shall we do it only when `EPHEMERAL_CLUSTER=tilt` ?

**Comment by Xenwar** [comment]
> Shall we clone CAPI all the time or shall we do it only when `EPHEMERAL_CLUSTER=tilt` ?

I would suggest all the time since cloning it is not that expensive. On the other hand, making it conditional just make the code bigger.

**Comment by kashifest** [comment]
> > Shall we clone CAPI all the time or shall we do it only when `EPHEMERAL_CLUSTER=tilt` ?
> 
> I would suggest all the time since cloning it is not that expensive. On the other hand, making it conditional just make the code bigger.

Ok. 
/lgtm

**Pull request merged**
