### PR TITLE
WIP test IRONIC_IMAGE env var

### PR DESCRIPTION
**Pull request by Rozzii**

### CODE REVIEW

**Comment by tuminoid** [comment]
> /cc @kashif
Damn autocomplete... 
/cc @kashifest

**Comment by kashifest** [comment]
I am bit lost what will this fix, is it the fix for the unser we talked offline? Can you add it in the description where the unset is done? How about keeping any value intact in between `make` and `make test`?

**Comment by tuminoid** [comment]
> I am bit lost what will this fix, is it the fix for the unset we talked offline? 

Yes.

> Can you add it in the description where the unset is done? 

It's @Rozzii PR.

> How about keeping any value intact in between `make` and `make test`?

I'm working on it elsewhere, this was just another finding in the whole 02 mess.

**Comment by Rozzii** [comment]
@kashifest @tuminoid  just one thing to keep in mind is that unsetting IRONIC_IMAGE is needed as otherwise we would have a conflicting upstream and localy built image

**Comment by Rozzii** [comment]
/close 
in favor or @tuminoid 's more comprehensive solution

**Pull request closed without merging**
