### PR TITLE
remove duplicates from OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by tuminoid**
Remove elfosardo and Rozzii from reviewers as they're on approvers list already.

They were left on in change https://github.com/metal3-io/metal3-dev-env/pull/1440

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-release-1-7  metal3-dev-env-integration-test-ubuntu-main

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
/approve
sorry my bad

**Pull request merged**
