### PR TITLE
Fix locale issue when checking for XFS compatibility

### PR DESCRIPTION
**Pull request by andfasano**
Filesystem type check failed when locale was not English. Thanks @hardys for the suggested solution.

### CODE REVIEW

**Comment by hardys** [comment]
@maelk hi, any idea why the *integration jobs didn't yet report back?

**Comment by hardys** [comment]
Hmm the integration test failure looks like a pip install issue:

```
[0;31m    "msg": "stdout: Collecting libvirt-python\n  Downloading https://files.pythonhosted.org/packages/cb/6e/72e1b6db7089068d3ef145e7af76bb9ffd94d20f3ed88e2ed66d6e0e4f8f/libvirt-python-6.0.0.tar.gz (196kB)\n    Complete output from command python setup.py egg_info:\n    libvirt-python requires Python 3.x to build\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-LuNCGz/libvirt-python/\n"[0m
```

That's unrelated to the change so perhaps we have a new problem

**Comment by fmuyassarov** [comment]
> Hmm the integration test failure looks like a pip install issue:
> 
> ```
> �[0;31m    "msg": "stdout: Collecting libvirt-python\n  Downloading https://files.pythonhosted.org/packages/cb/6e/72e1b6db7089068d3ef145e7af76bb9ffd94d20f3ed88e2ed66d6e0e4f8f/libvirt-python-6.0.0.tar.gz (196kB)\n    Complete output from command python setup.py egg_info:\n    libvirt-python requires Python 3.x to build\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-LuNCGz/libvirt-python/\n"�[0m
> ```
> 
> That's unrelated to the change so perhaps we have a new problem

This issue is fixed now with [PR#193](https://github.com/metal3-io/metal3-dev-env/pull/193). 
@andfasano can you please rebase your commit

**Pull request merged**
