### PR TITLE
Replace shell task that obtains target cluster kubeconfig with k8s_info module

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR replaces the first shell task in Ansible move tasks from the integration tests roles by k8s_info module

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
@mboukhalfa you have to rebase your PR and re-trigger centos test, that should pass.

**Comment by mboukhalfa** [comment]
I am closing this PR since updates already tested and integrated on PR  #672

**Pull request closed without merging**
