### PR TITLE
Install ansible in a virtual environment

### PR DESCRIPTION
**Pull request by dtantsur**
Installing packages globally with pip is not recommended since such
packages may conflict with the system. Using a virtual environment is
the approach we have employed in Bifrost for a long time, let's do the
same here.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by tuminoid** [comment]
/test metal3-dev-env-integration-test-centos-main 
Python installations are somewhat different, so let's run centos as well.

**Comment by dtantsur** [comment]
> Python installations are somewhat different, so let's run centos as well.

Yeah, I wanted one job to pass before I occupy the CI with the rest :)

**Comment by tuminoid** [comment]
> > Python installations are somewhat different, so let's run centos as well.
> 
> Yeah, I wanted one job to pass before I occupy the CI with the rest :)

Ubuntu progressed, so ... :) 

Centos will probably fail tho, there seems to be again some issue with the new cloud + Centos, but it'll probably pass far enough to tell if venv worked or not.

**Comment by tuminoid** [comment]
Don't bother with Centos right now, we're debugging Centos main as all centos e2e are failing now, as VMs are not coming up and hence BMHs are not ever inspected.

**Comment by tuminoid** [comment]
/override metal3-dev-env-integration-test-centos-main 
Not required even, skip.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
