### PR TITLE
Fix environment variable export for feature test upgrade

### LINKED ISSUE #418: Feature test upgrade environment variables are not exported properly
The env variables exported for feature test upgrade are exported in a way that falls within the sub-shell during the call and the variables are not known outside the subshell. The current declaration is here:

https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/setup_env.sh#L8,9 

As a result, when generating the cluster template, the correct CAPM3 version is not looked for and the following error occurs:

```
TASK [v1aX_integration_test : Generate clusterctl cluster template] ***********************************************************************************************************
task path: /home/airshipci/metal3-dev-env/vm-setup/roles/v1aX_integration_test/tasks/generate_templates.yml:13
failed: [localhost] (item=cluster) => {
    "ansible_loop_var": "item",
    "changed": false,
    "checksum": "fe1d63da0b25dbd1ebfd5483d31e17827f14583e",
    "diff": [],
    "invocation": {
        "module_args": {
            "_original_basename": "cluster-template-cluster.yaml",
            "attributes": null,
            "backup": false,
            "checksum": "fe1d63da0b25dbd1ebfd5483d31e17827f14583e",
            "content": null,
            "delimiter": null,
            "dest": "/home/airshipci/.cluster-api/overrides/infrastructure-metal3/v0.4.0/cluster-template-cluster.yaml",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "group": null,
            "local_follow": null,
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/home/airshipci/.ansible/tmp/ansible-tmp-1597055333.5359867-100892241034525/source",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "item": "cluster",
    "msg": "Destination directory /home/airshipci/.cluster-api/overrides/infrastructure-metal3/v0.4.0 does not exist"
}

```

### PR DESCRIPTION
**Pull request by kashifest**
Fixes #418

### CODE REVIEW

**Comment by maelk** [comment]
I'm not sure I get the logic behind moving those two variables in their own file if that file is only referenced there. What impact does this have ?

**Comment by kashifest** [comment]
> I'm not sure I get the logic behind moving those two variables in their own file if that file is only referenced there. What impact does this have ?

Those export seem to remain in the subshell and undefined outside of the call. Sourcing them makes sure the variables keep being defined across the shells.

**Comment by kashifest** [comment]
/hold
Until feature feature test upgrade is available in CI

**Comment by Jaakko-Os** [comment]
I tested this fix in metal3-dev-env. I run into the same issue as before using the fix:

`Error: failed to get provider components for the "metal3:v0.3.2" provider: failed to perform variable substitution: value for variables [DEPLOY_KERNEL_URL, DEPLOY_RAMDISK_URL, IRONIC_INSPECTOR_URL, IRONIC_URL] is not set. Please set the value using os environment variables or the clusterctl config file`

'export' should make the variables visible to subshells?

**Comment by maelk** [comment]
> > I'm not sure I get the logic behind moving those two variables in their own file if that file is only referenced there. What impact does this have ?
> 
> Those export seem to remain in the subshell and undefined outside of the call. Sourcing them makes sure the variables keep being defined across the shells.

which subshell are you talking about ? if it needs to be defined in the parent script, it could be just moved there, no ? export will make the variables available to any subshell as environment variable.

Can you please clearly state the problem that you have been hitting ?

**Comment by kashifest** [comment]
Closing this Issue since #428 is taking these changes.
/close

**Pull request closed without merging**
