### PR TITLE
Cached images are stored in http://$PROVISIONING_URL_HOST/images/

### PR DESCRIPTION
**Pull request by MaXinjian**
Cached images are stored in http://172.22.0.1/images not http://172.22.0.2/images

Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> Thank you. Do you want to fix it in Baremetal Operator too?
> https://github.com/metal3-io/baremetal-operator/blob/6ce7bc31d9e164119bdf6706b28417298e42865b/ironic-deployment/keepalived/ironic_bmo_configmap.env#L10

@fmuyassarov it is already `.1` IP address.

**Comment by fmuyassarov** [comment]
> > Thank you. Do you want to fix it in Baremetal Operator too?
> > https://github.com/metal3-io/baremetal-operator/blob/6ce7bc31d9e164119bdf6706b28417298e42865b/ironic-deployment/keepalived/ironic_bmo_configmap.env#L10
> 
> @fmuyassarov it is already `.1` IP address.

Ops, sorry. @MaXinjian please ignore my above comment.

**Comment by fmuyassarov** [comment]
@furkatgofurov7 why is PROVISIONING_IP is set to 172.22.0.2 but not 172.22.0.1 in ironic_bmo_configmap.env?

**Comment by furkatgofurov7** [comment]
@fmuyassarov yes, in 03_* we also set PROVISIONING_IP to .2 IP afaik.

**Comment by MaXinjian** [comment]
ping？

**Pull request merged**
