### PR TITLE
✨Drop CentOS8.3 and move to CentOS Stream

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This is the second try to move to CentOS Stream in metal3-dev-env. 

Fixes: #671

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/hold
/retitle ✨Drop CentOS8.3 and move to CentOS Stream

It needs [airship#327](https://github.com/Nordix/airship-dev-tools/pull/327) to go in first to build metal3/node centos images and pass centos integration/feature tests.

**Review by lentzi90 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
airship#327 is merged and images are built, triggering the tests. 

/test-v1a4-centos-integration
/test-centos-integration
/test-features-centos

**Review by fmuyassarov — COMMENTED** [review]
/approve

**Pull request merged**
