### PR TITLE
✨Run feature tests with v1beta1 API

### PR DESCRIPTION
**Pull request by namnx228**
/hold

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/retitle ✨Run feature tests with v1beta1 API

**Comment by furkatgofurov7** [comment]
@namnx228 do we need this testing PR anymore?

**Comment by namnx228** [comment]
@furkatgofurov7 No, we don't
/close

**Comment by furkatgofurov7** [comment]
/close

That was for testing a command.

**Pull request closed without merging**
