### PR TITLE
Add ansible profile_tasks callback to print tasks timing

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR add timing information to Ansible tasks using [profile_tasks](https://docs.ansible.com/ansible/latest/collections/ansible/posix/profile_tasks_callback.html) that can help identify tasks consuming time and optimize tests.
Fix the config file `ansible.cfg` reference in feature_tests playbooks

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Does the time get printed in the console after every task?

**Comment by mboukhalfa** [comment]
> Does the time get printed in the console after every task?

There are different information in each task `such start time (task delay) playbook delay` after each task and also there is a summary at the end of the playbook. 
Check more info [in docs](https://docs.ansible.com/ansible/latest/collections/ansible/posix/profile_tasks_callback.html)

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
