### PR TITLE
Added a bug report template

### PR DESCRIPTION
**Pull request by harshithakolipaka**

### CODE REVIEW

**Review by furkatgofurov7 — CHANGES_REQUESTED** [review]
Hey, thanks for working on this!

As I described in the [issue](https://github.com/metal3-io/metal3-dev-env/issues/1078#issue-1382413859), it would be great if we could reuse (with needed modifications) the existing issue templates we have in other repos, i.e: https://github.com/metal3-io/cluster-api-provider-metal3/tree/main/.github/ISSUE_TEMPLATE.

Please also note, templates are usually placed under `.github/ISSUE_TEMPLATE/` folder with common name and format `bug_report.md`

**Review by tuminoid — CHANGES_REQUESTED** [review]
Hi @harshithakolipaka, thanks for the PR. 

1. This file should go to `.github/ISSUE_TEMPLATE/bug_report.md`. 
2. This file needs to have repository specific format, to help triage the bug. It should query about reporter's `IMAGE_OS`, `EPHEMERAL_CLUSTER` and other key configurations. It isn't very relevant to ask for what Windows do they have, or what web browser they use.

**Review by mboukhalfa — CHANGES_REQUESTED** [review]
Check the template example on capm3 repo here https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Consider the dev-env inputs from here : https://github.com/metal3-io/metal3-dev-env#environment-variables

**Comment by furkatgofurov7** [comment]
@harshithakolipaka can you please fix the markdown issues on this PR?

**Pull request closed without merging**
