### PR TITLE
🌱Increase retry of verifying number of ready m3machine resources

### PR DESCRIPTION
**Pull request by Sunnatillo**
Increase timeout of verifying number of m3machine  resources.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
BML test were failing due to timeout. the ones which passed the verify task were passing it on 8th, 9th try. Increasing timeout should solve the timeout in bml tests. 
Failed tests: [#158](https://jenkins.nordix.org/job/airship_master_bml_integration_tests_centos/158/consoleFull), [#163](https://jenkins.nordix.org/job/airship_master_bml_integration_tests_centos/163/consoleFull), [#61](https://jenkins.nordix.org/job/airship_metal3io_project_infra_bml_integration_tests_centos/61/consoleFull)

**Review by lentzi90 — COMMENTED** [review]
/lgtm
The BML  seems to be slower in many cases. I wonder why? Maybe it has slow disks? Or physical hosts just takes more time in general?

**Comment by macaptain** [comment]
> /lgtm The BML seems to be slower in many cases. I wonder why? Maybe it has slow disks? Or physical hosts just takes more time in general?

It's because powering on a physical host takes 5-10 minutes (getting through POST, BIOS screen, hardware checks, raid controller initialization, etc.), whereas starting a virtual machine is more or less instant.

**Review by furkatgofurov7 — APPROVED** [review]
/retitle 🌱Increase retry of verifying number of ready m3machine resources
/approve

**Pull request merged**
