### PR TITLE
Change some env var names to same ones in CAPI

### PR DESCRIPTION
**Pull request by mquhuy**
Some settings are being referred to using different env vars in this repo than in CAPI and CAPM3. In here we change
- `NUM_OF_CONTROLPLANE_REPLICAS`  => `CONTROL_PLANE_MACHINE_COUNT`
- `NUM_OF_WORKER_REPLICAS` => `WORKER_MACHINE_COUNT`

### CODE REVIEW

**Comment by tuminoid** [comment]
lgtm

**Comment by smoshiur1237** [comment]
Do we need to run feature test on this PR? otherwise LGTM from my side.

**Comment by lentzi90** [comment]
Good point, maybe some e2e test would be good!

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by furkatgofurov7 — APPROVED** [review]

**Pull request merged**
