### PR TITLE
🌱 Update kustomize and kind versions to latest

### PR DESCRIPTION
**Pull request by furkatgofurov7**

### CODE REVIEW

**Review by maelk — COMMENTED** [review]
Can you maybe split this PR into two ? one for the actual kustomize and kind changes and a second for the visual changes / comments ?

**Comment by furkatgofurov7** [comment]
> Can you maybe split this PR into two ? one for the actual kustomize and kind changes and a second for the visual changes / comments ?

Sure, I will open a follow-up PR.

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
