### PR TITLE
Follow-up to #508

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This PR addresses comments from #508

### CODE REVIEW

**Review by maelk — APPROVED** [review]

**Comment by maelk** [comment]
Please run also the feature tests on this

**Comment by furkatgofurov7** [comment]
CAPM3 v0.4.1 was released in between when running the tests, so it failed, re-triggering should help. 

/test-centos-integration

**Review by fmuyassarov — COMMENTED** [review]
looks good to me!

**Pull request merged**
