### PR TITLE
:seedling: Bump k8s to 1.32.0

### PR DESCRIPTION
**Pull request by peppi-lotta**
Bump k8s to 1.32.0

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/test metal3-centos-e2e-integration-test-release-1-8 metal3-dev-env-integration-test-ubuntu-main

**Comment by tuminoid** [comment]
```text
[2024-12-16T06:46:54.263Z] ++ [[ https://artifactory.nordix.org/artifactory/metal3/images/k8s_v1.32.0 =~ ^http.* ]]

[2024-12-16T06:46:54.263Z] ++ wget --no-verbose --no-check-certificate https://artifactory.nordix.org/artifactory/metal3/images/k8s_v1.32.0/UBUNTU_22.04_NODE_IMAGE_K8S_v1.32.0.qcow2

[2024-12-16T06:46:54.612Z] https://artifactory.nordix.org/artifactory/metal3/images/k8s_v1.32.0/UBUNTU_22.04_NODE_IMAGE_K8S_v1.32.0.qcow2:

[2024-12-16T06:46:54.612Z] 2024-12-16 06:46:54 ERROR 404: Not Found.
```

This needs images to be built.
/hold

**Comment by adilGhaffarDev** [comment]
> This needs images to be built.

PRs for 1.32 node image building are merged, but the periodic job failed that's why there are no images, I have retriggered the node image building job. https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_node_image_building/107/

**Pull request merged**
