### PR TITLE
Fix README link to Getting started with Metal3

### PR DESCRIPTION
**Pull request by clobrano**
Sorry for the silly PR, but I noticed the link was broken.

### CODE REVIEW

**Comment by tuminoid** [comment]
It is not silly, if its broken :) 

The try-it URL was recently moved in metal3-docs, so good catch.

/ok-to-test

/override test-centos-integration-release-1-5 
/override test-ubuntu-e2e-integration-main 

Integration tests do nothing for readme.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve
Thanks for the contribution! No such thing as silly PRs :slightly_smiling_face:

**Comment by clobrano** [comment]
Thanks :smiley:

**Pull request merged**
