### PR TITLE
🌱 Uplift k8s to v1.31.2

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
- bump k8s to v1.31.2
- KIND_VERSION to v0.24.0
- KIND_NODE_IMAGE_VERSION to v1.31.0

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
> bump k8s to v1.31.1

Typo in the description. Should be v1.31.2.

/approve

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
