### PR TITLE
Temporary pin ironic-standalone-operator image

### PR DESCRIPTION
**Pull request by dtantsur**
We're going to merge a few API breaking changes in preparation for the
MVP release. To ensure that metal3-dev-env can be used in the meantime,
pin the image to the current digest.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/retest
Flake

**Comment by dtantsur** [comment]
/test metal3-centos-e2e-integration-test-release-1-8 

The ubuntu job is past the IrSO configuration point.

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Comment by dtantsur** [comment]
> Failed to inspect hardware. Reason: unable to start inspection: Validation
    of image href http://172.22.0.2:6180/images/ironic-python-agent.kernel failed,
    reason: Got HTTP code 404 instead of 200 in response to HEAD request.

This is without IrSO though, so should not be related.

**Comment by dtantsur** [comment]
/test metal3-dev-env-integration-test-ubuntu-main

IPA-downloader did not finish downloading from tarballs.opendev.org

**Comment by dtantsur** [comment]
> Could not resolve host: github.com

/test metal3-dev-env-integration-test-ubuntu-main

**Pull request merged**
