### PR TITLE
fix ipaddress import failure

### PR DESCRIPTION
**Pull request by Jaakko-Os**
due to missing import, ipcalc was also failing

### CODE REVIEW

**Comment by maelk** [comment]
What about CentOS ? Would the same problem happen ?

**Comment by Jaakko-Os** [comment]
> What about CentOS ? Would the same problem happen ?

seems to be fine in centos since the integration tests pass

**Comment by maelk** [comment]
the integration tests are also passing for Ubuntu, even if ipcalc is not installed properly. Did you verify if ipcalc is installed on centOS properly ?

**Comment by Jaakko-Os** [comment]
No. Closing this PR.

**Pull request closed without merging**
