### PR TITLE
Add verification for v1alpha2 deployment

### PR DESCRIPTION
**Pull request by fmuyassarov**
This patch adds: 
- minor change in v1alpha1 Replicasets verification;
- verification for v1alpha2 Pods, Deployments, CRDs and Replicasets

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold 
Need to test updated verification functions against v1alpha1

**Comment by kashifest** [comment]
lgtm

**Comment by fmuyassarov** [comment]
/assign @Xenwar 
@Jaakko-Os 
@mikkosest

**Pull request merged**
