### PR TITLE
remove unsupported OSes

### PR DESCRIPTION
**Pull request by tuminoid**
We are not supporting CentOS 8 (EOL), Ubuntu 18 (soon to be EOL) or proprietary RHEL distros in this development environment repository. Remove the last references of those distros.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold

To be discussed in Community Meeting first for the RHEL removal.

**Comment by dtantsur** [comment]
I'd prefer you keep RHEL, I think some of us are running it.

**Comment by tuminoid** [comment]
Were keeping support: https://github.com/metal3-io/cluster-api-provider-metal3/pull/882#issuecomment-1460251628

/close

**Pull request closed without merging**
