### PR TITLE
Modify the v1alpha2 deployment script

### PR DESCRIPTION
**Pull request by maelk**
Modifications to successfully deploy a two nodes cluster (centos and ubuntu)

### CODE REVIEW

**Comment by maelk** [comment]
/cc kashifest
/cc jan-est 
/cc fmuyassarov
@xenwar

**Comment by kashifest** [comment]
lgtm. Well doen @maelk . Lets wait for a fresh pair of eyes.

**Comment by fmuyassarov** [comment]
lgtm

**Comment by maelk** [comment]
I have refactored the CR generation part, to have them as files for both ubuntu and centos. It is easier to read IMO.

**Pull request merged**
