### PR TITLE
Change k8s to 1.20.0

### PR DESCRIPTION
**Pull request by kashifest**
This is necessary to keep the upgrade workflow going until 1.20.3 is
released. Once 1.20.3 is released we can switch m3-dev-env k8s version
to 1.20.2 .

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
You might need to make the similar changes in airship-dev-tools repo, to build the images with the latest changes related to docker. Or, build the images locally from the latest airship-dev-tools and push it to the artifactory.

**Comment by kashifest** [comment]
> You might need to make the similar changes in airship-dev-tools repo, to build the images with the latest changes related to docker. Or, build the images locally from the latest airship-dev-tools and push it to the artifactory.

Duh!!! True :(

**Review by namnx228 — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/approve
/hold
until we run test with the latest CI images

**Comment by fmuyassarov** [comment]
@kashifest feel free to remove the hold after CI passed

**Pull request merged**
