### PR TITLE
Clean up sushy-tools and vbmc Dockerfiles

### PR DESCRIPTION
**Pull request by fmuyassarov**
We have migrated (in https://github.com/metal3-io/ironic-image/pull/267) sushy-tools and vbmc Dockerfiles to [Ironic-image](https://github.com/metal3-io/ironic-image/tree/master/resources) repository, and Quay is configured to build images from Ironic-image repository. As such, this is to clean up old Dockerfiles.

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
@fmuyassarov can you please paste a link to the PR description where you migrated it to ironic-image repo? Thanks. 

/approve

**Comment by fmuyassarov** [comment]
> @fmuyassarov can you please paste a link to the PR description where you migrated it to ironic-image repo? Thanks.
> 
> /approve

@furkatgofurov7 done

**Review by bfournie — APPROVED** [review]

**Pull request merged**
