### PR TITLE
Fix local run config for BMO+Ironic container

### PR DESCRIPTION
**Pull request by mikkosest**
Trigger for run local Ironic containers was missing

### CODE REVIEW

**Comment by hardys** [comment]
By default ironic now runs on the minikube cluster ref https://github.com/metal3-io/metal3-dev-env/pull/68 so I'm not sure we want to add this, or if we do it should probably be configurable?

/cc @stbenjam

**Comment by mikkosest** [comment]
> By default ironic now runs on the minikube cluster ref #68 so I'm not sure we want to add this, or if we do it should probably be configurable?
> 
> /cc @stbenjam

I agree that this is only for debugging and verification needs. The code change is under BMO_RUN_LOCAL flag, so it is executed only when user really wants to run local BMO+Ironic
setup. 
    if [ "${BMO_RUN_LOCAL}" = true ]; then
      touch bmo.out.log
      touch bmo.err.log
      kustomize build "$kustomize_overlay_path" | kubectl apply -f-
      kubectl scale deployment metal3-baremetal-operator -n metal3 --replicas=0
      ${RUN_LOCAL_IRONIC_SCRIPT}

**Comment by hardys** [comment]
> The code change is under BMO_RUN_LOCAL flag, so it is executed only when user really wants to run local BMO+Ironic
setup.

Ah sorry I see that now, the conditional was hidden by the github UI folding the previous code, looks good then

**Pull request merged**
