### PR TITLE
Update build status links for dev env tests

### PR DESCRIPTION
**Pull request by Sunnatillo**
This PR updates build status links for dev env tests and remove old tests

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/override metal3-centos-e2e-integration-test-release-1-7 metal3-dev-env-integration-test-ubuntu-main

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-release-1-7 metal3-dev-env-integration-test-ubuntu-main

**Pull request merged**
