### PR TITLE
📖 Remove v1a4 main job CI badges from Readme

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Depends on:

- https://gerrit.nordix.org/c/infra/cicd/+/12300
- https://github.com/metal3-io/cluster-api-provider-metal3/pull/509

The idea is, we won't be running v1a4 main jobs daily, but we still do run v1a4 integration tests on PRs per need basis.

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
Notice period has ended today and there were no objections till now on this PR/ slack channel or mailing list, so unholding it.

/hold cancel

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
