### PR TITLE
Upgrade test Makefile update

### PR DESCRIPTION
**Pull request by Jaakko-Os**

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
lgtm

**Comment by fmuyassarov** [comment]
Can we also add upgrade target in the root Makefile with this PR? or should it go in a separate PR?

**Comment by maelk** [comment]
maybe you should run / test-features too ?

**Comment by fmuyassarov** [comment]
> maybe you should run / test-features too ?

It will not run upgrade tests anyway because upgrade Makefile target is currently excluded from root Makefile.

**Comment by kashifest** [comment]
> > maybe you should run / test-features too ?
> 
> It will not run upgrade tests anyway because upgrade Makefile target is currently excluded from root Makefile.

True. Once we are sure that upgrade tests are running properly with the framework, we can push the root Makefile changes also in the same PR. @Jaakko-Os  whats the status of upgrade tests? Are they running OK with the framework?

**Comment by Jaakko-Os** [comment]
> > > maybe you should run / test-features too ?
> > 
> > 
> > It will not run upgrade tests anyway because upgrade Makefile target is currently excluded from root Makefile.
> 
> True. Once we are sure that upgrade tests are running properly with the framework, we can push the root Makefile changes also in the same PR. @Jaakko-Os whats the status of upgrade tests? Are they running OK with the framework?

Lets hold the root Makefile change. Upgrade tests are being run but some issues need to be fixed.

**Pull request merged**
