### PR TITLE
Move list of vars from try-it.md to Readme here

### PR DESCRIPTION
**Pull request by fmuyassarov**
Move list of all the environment variables from `try-it.md` to `Readme.md ` here so that we keep all of those vars updated and synchronized with the related changes in Metal3-dev-env. 
Related to [#185](https://github.com/metal3-io/metal3-io.github.io/pull/185)

### CODE REVIEW

**Comment by maelk** [comment]
lgtm, but I'd like to know if this move is okay for some other people, like @russellb and the people that have been maintaining the website.

**Comment by fmuyassarov** [comment]
> lgtm, but I'd like to know if this move is okay for some other people, like @russellb and the people that have been maintaining the website.

Related PR in metal3-io.github.io: https://github.com/metal3-io/metal3-io.github.io/pull/185

**Comment by russellb** [comment]
Seems fine to me.  That's probably more detail than necessary for the quick-start guide and more of reference material that can be here

**Pull request merged**
