### PR TITLE
Fix tilt setup script after the removal of ironic-inspector

### PR DESCRIPTION
**Pull request by maxrantil**
A bug appeared after the removal of the ironic-inspector. The ironic-inspector-secret was used for ironic and vice versa. This fix will address that issue and also remove the ironic-inspector from our tilt-setup.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
wondering if this would work with older release branches now. Shall we add `if..else ` instead

**Comment by maxrantil** [comment]
@kashifest What conditions can I use for the if statement? I changed it back to only fix the bug now. I think we can keep the ironic-inspector code if older branches still use it. I didn't think about that before.

**Comment by maxrantil** [comment]
My bad, we need the `if, else` statement, and I noticed I can check on `IRONIC_INSPECTOR_URL` for that.

**Comment by maxrantil** [comment]
I tried removing `IRONIC_INSPECTOR_URL": "${IRONIC_INSPECTOR_URL}`, from the tilt-settings.json file with an if-statement from the script. But that was not straight-forward. Removing it is only a matter of having a neater tilt-settings.json file. For now, this approach should be compatible with both old and new branches.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
