### PR TITLE
debug ironic database locked issue

### PR DESCRIPTION
**Pull request by Sunnatillo**
This is a test PR to recreate ironic database locked issue. 
Related to https://github.com/metal3-io/ironic-image/pull/430. 
We run more test  cases to reproduce the issue.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
We have been able to reproduce the issue here:
https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_centos/19/

**Comment by Sunnatillo** [comment]
This tests reproduces ironic database as well:
https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_ubuntu/9

**Comment by Sunnatillo** [comment]
Db locked occured once more here:
https://jenkins.nordix.org/job/metal3_metal3_dev_env_main_e2e_integration_test_centos/20/

**Comment by dtantsur** [comment]
Okay, interesting. It only failed at whatever stage is captured in `final_logs`, which does not seem to include my changes from the PR.

/test-centos-integration-release-1-5
/test-centos-integration-release-1-4
/test-centos-integration-release-1-3
/test-ubuntu-integration-release-1-5
/test-ubuntu-integration-release-1-4
/test-ubuntu-integration-release-1-3
/test-ubuntu-e2e-integration-main
/test-ubuntu-e2e-integration-release-1-5
/test-centos-e2e-integration-main
/test-centos-e2e-integration-release-1-5

**Comment by Sunnatillo** [comment]
> Okay, interesting. It only failed at whatever stage is captured in `final_logs`, which does not seem to include my changes from the PR.
> 
> /test-centos-integration-release-1-5 /test-centos-integration-release-1-4 /test-centos-integration-release-1-3 /test-ubuntu-integration-release-1-5 /test-ubuntu-integration-release-1-4 /test-ubuntu-integration-release-1-3 /test-ubuntu-e2e-integration-main /test-ubuntu-e2e-integration-release-1-5 /test-centos-e2e-integration-main /test-centos-e2e-integration-release-1-5

Can you insert a link to the test you are checking? I will check what is the issue.

**Comment by dtantsur** [comment]
@Sunnatillo I think it was https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-3_integration_test_ubuntu/24/

**Comment by dtantsur** [comment]
/test-centos-integration-release-1-5
/test-centos-integration-release-1-4
/test-centos-integration-release-1-3
/test-ubuntu-integration-release-1-5
/test-ubuntu-integration-release-1-4
/test-ubuntu-integration-release-1-3
/test-ubuntu-e2e-integration-main
/test-ubuntu-e2e-integration-release-1-5
/test-centos-e2e-integration-main
/test-centos-e2e-integration-release-1-5

Our patches got merged, updated the testing PR accordingly.

**Comment by dtantsur** [comment]
/test-centos-integration-release-1-5
/test-centos-integration-release-1-4
/test-centos-integration-release-1-3
/test-ubuntu-integration-release-1-5
/test-ubuntu-integration-release-1-4
/test-ubuntu-integration-release-1-3
/test-ubuntu-e2e-integration-main
/test-ubuntu-e2e-integration-release-1-5
/test-centos-e2e-integration-main
/test-centos-e2e-integration-release-1-5

The only red job failed for another reason ("Client-side error: Node d72dc383-33db-4622-817d-fe216a8b7a56 is associated with instance")

**Pull request closed without merging**
