### PR TITLE
bump k8s to v1.30.0

### PR DESCRIPTION
**Pull request by kashifest**
also bumps kind node image

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Tide hello.... 
/retitle bump k8s to v1.30.0

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-release-1-6 
/unhold
Prow and GH branch protection mismatched.

**Comment by tuminoid** [comment]
> /test-centos-integration-release-1-7

This probably won't work or tests wrong stuff, since https://github.com/metal3-io/metal3-dev-env/pull/1381 is not merged.

**Comment by kashifest** [comment]
> > /test-centos-integration-release-1-7
> 
> This probably won't work or tests wrong stuff, since #1381 is not merged.

Its testing main actually, as discussed offline we should fail here instead of testing main, I will try to push a fix later today.

**Comment by tuminoid** [comment]
/hold
Its testing wrong stuff.

**Comment by tuminoid** [comment]
1381 is merged, rebase.

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-release-1-7
to get it configured

**Review by smoshiur1237 — APPROVED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
