### PR TITLE
Wait for controlplane pods to be Ready before proceeding with Calico

### PR DESCRIPTION
**Pull request by fmuyassarov**
/cc @kashifest @lentzi90

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
I think it is kube-proxy that is causing the issue actually, not the control-plane components. But I guess the real question is why this started happening suddenly? :thinking: Does anyone know if kube-proxy used to be baked in the image?

**Comment by fmuyassarov** [comment]
> I think it is kube-proxy that is causing the issue actually, not the control-plane components. But I guess the real question is why this started happening suddenly? thinking Does anyone know if kube-proxy used to be baked in the image?

my bad, I forgot to add the kube-proxy :)

**Comment by fmuyassarov** [comment]
> I think it is kube-proxy that is causing the issue actually, not the control-plane components. But I guess the real question is why this started happening suddenly? thinking Does anyone know if kube-proxy used to be baked in the image?

I don't think we back kube-proxy image, it is stored in Google container registry, and we don't usually had pulling issues like we have with Docker registry.

**Comment by lentzi90** [comment]
I think I found the issue. The changes I made to centos cloud-init affected both metal3 and node images (I thought it was only metal3). This PR should hopefully fix it: https://github.com/Nordix/metal3-dev-tools/pull/522

**Comment by mboukhalfa** [comment]
@lentzi90 can we close this PR ?

**Comment by lentzi90** [comment]
Yes it is fine by me to close it.

**Pull request closed without merging**
