### PR TITLE
add support for release-1.9

### PR DESCRIPTION
**Pull request by tuminoid**
Add support for release-1.9.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Until we have releases done and JJBs https://gerrit.nordix.org/c/infra/cicd/+/22800 etc

**Review by kashifest — COMMENTED** [review]
Remove 1.6 as well?

**Comment by tuminoid** [comment]
> Remove 1.6 as well?

We have agreed to follow best practice of not mixing adding and removing in same PR. there is another PR for removals.

**Comment by kashifest** [comment]
> We have agreed to follow best practice of not mixing adding and removing in same PR. There ~is~ will be another PR for removals.

Did we? I am fine either ways, IMHO the removal in the same PR makes more sense so as to we dont forget 
/approve

**Comment by tuminoid** [comment]
> > We have agreed to follow best practice of not mixing adding and removing in same PR. There ~is~ will be another PR for removals.
> 
> Did we? I am fine either ways, IMHO the removal in the same PR makes more sense so as to we dont forget /approve

Yes. They make diffs harder to read, and also sometimes contain unrelated stuff. Makes also reverting impossible and also referring to PRs from other PRs or isssues obscure as it is not clear from the title/changes. Also timing for adding and removing might be different.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Let's see about this chicken and egg issue with this and https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164

**Pull request merged**
