### PR TITLE
Remove release-0.5 mentions in dev-env

### PR DESCRIPTION
**Pull request by mquhuy**
As title

### CODE REVIEW

**Review by Sunnatillo — DISMISSED** [review]
/lgtm

**Comment by adilGhaffarDev** [comment]
LGTM

**Review by kashifest — DISMISSED** [review]

**Comment by furkatgofurov7** [comment]
/hold

Do not we still need this as per: https://github.com/metal3-io/cluster-api-provider-metal3/blob/5ebb78cdbee8fb72ed3a6191d142f86eb4d635f1/README.md#upgrade-tests or the notes has to be updated if that is not accurate

**Comment by Sunnatillo** [comment]
> /hold
> 
> Do not we still need this as per: https://github.com/metal3-io/cluster-api-provider-metal3/blob/5ebb78cdbee8fb72ed3a6191d142f86eb4d635f1/README.md#upgrade-tests or the notes has to be updated if that is not accurate

yes. But that part handled in capm3, we do not use dev env to initialize v1alpha5 cluster for upgrade tests.

**Comment by furkatgofurov7** [comment]
> yes. But that part handled in capm3, we do not use dev env to initialize v1alpha5 cluster for upgrade tests. v1alpha5 is not supported. But we support upgrading from v1alpha5. It is ok to remove it from dev-env.

I am not sure I got that and think notes in CAPM3 has to be updated. If it is not supported then there should not be an upgrade test mentions in CAPM3.. 

/hold cancel

**Pull request merged**
