### PR TITLE
Update Ansible dependency to v5

### PR DESCRIPTION
**Pull request by furkatgofurov7**

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
I opened this to debug #982 but at the end (after uplifting to CentOS Stream 9) there was nothing to do other than just uplifting the version :). #982 needs a bot to rebase and rerunning the tests so instead, we can just take this in instead and drop 982. 

/cc @kashifest @smoshiur1237

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
