### PR TITLE
🐛 Fix the issue that tripleo-repo requires a stream version of OS to run properly. 

### PR DESCRIPTION
**Pull request by namnx228**
This temporary fix the issue `__main__.InvalidArguments: --stream provided, but OS is not the Stream version. Please ensure the host is Stream.` in Dockerfile of vbmc

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
Can't we still use a single RUN?
Can you please update the PR title to reflect what you are fixing here?

**Comment by namnx228** [comment]
> Can't we still use a single RUN?
> Can you please update the PR title to reflect what you are fixing here?

Sure, I will change the title

**Comment by kashifest** [comment]
Can't we use the `[--no-stream](https://github.com/openstack/tripleo-repos/blob/master/releasenotes/notes/stream_by_default-783cc6a2208b942c.yaml#L4-L5)` flag instead ? Or a centros-stream image? By the way, isn't is so that the `vbmc` image is built on master jobs only? Integration tests are still not broken with this right?

**Comment by namnx228** [comment]
> Can't we use the [--no-stream](https://github.com/openstack/tripleo-repos/blob/master/releasenotes/notes/stream_by_default-783cc6a2208b942c.yaml#L4-L5) flag instead ? Or a centros-stream image? By the way, isn't is so that the `vbmc` image is built on master jobs only? Integration tests are still not broken with this right?

I have tried to to used the `--no-stream` flag, but it doesn't work. 
I am not sure about other PRs, but I think the integration tests for this PR should pass the CI since the vbmc is built based on the Dockerfile of this PR.

**Comment by namnx228** [comment]
@kashifest Using centos stream can be a long term solution, but we need to have more discussion before adopting it. Therefore, let's use this temporary fix to make the CI master jobs pass asap.

**Comment by fmuyassarov** [comment]
> Can't we use the [--no-stream](https://github.com/openstack/tripleo-repos/blob/master/releasenotes/notes/stream_by_default-783cc6a2208b942c.yaml#L4-L5) flag instead ? Or a centros-stream image? By the way, isn't is so that the `vbmc` image is built on master jobs only? Integration tests are still not broken with this right?

No, we enabled them for every PR on metal3-dev-env

**Review by fmuyassarov — APPROVED** [review]
Merging this now to unblock the Jenkins CI. This is happening after https://github.com/openstack/tripleo-repos/commit/e91bd735f7cb2124e9bf873614dcd47e24e1ea88 change. We need to probably pass the stream flag.
/cc @hardys

**Pull request merged**
