### PR TITLE
Refactor deployment and test scripts

### PR DESCRIPTION
**Pull request by maelk**
This commit reduces the number of times the Github API is called
to fetch the releases, and reorganizes the tests to remove duplication

### CODE REVIEW

**Comment by maelk** [comment]
@fmuyassarov it looks like it is the wrong node that gets notReady. Is that something you've seen already ?

**Comment by fmuyassarov** [comment]
> @fmuyassarov it looks like it is the wrong node that gets notReady. Is that something you've seen already ?

Yes, sorry for that. We missed to add `sort` in some places. Basically,` kubectl get nodes` doesn't print nodes in the right order, that's why it is failing. Here is the fix https://github.com/metal3-io/metal3-dev-env/pull/406

**Comment by fmuyassarov** [comment]
@maelk would you mind to rebase your branch please?

**Comment by maelk** [comment]
The CI should do it normally :/

**Comment by fmuyassarov** [comment]
> The CI should do it normally :/

Hum, yes you are right.

**Comment by fmuyassarov** [comment]
> The CI should do it normally :/

That's really weird that we are still seeing the same issue even after the fix.

**Comment by maelk** [comment]
We found a bug in the features tests, @fmuyassarov will fix it. merging this one meanwhile

**Pull request merged**
