### PR TITLE
Enable upgrade test for ubuntu.

### PR DESCRIPTION
**Pull request by smoshiur1237**

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Should we wait until https://github.com/metal3-io/project-infra/pull/168 gets merged?

**Comment by smoshiur1237** [comment]
Yes we should wait for that PR to get merged

**Comment by smoshiur1237** [comment]
This  [metal3-io/project-infra#168](https://github.com/metal3-io/project-infra/pull/168)  PR need to get merge first.
/hold

**Review by kashifest — APPROVED** [review]

**Comment by fmuyassarov** [comment]
@smoshiur1237 How are you making sure that you taking CAPIRELEASE value set in project-infra?

**Comment by smoshiur1237** [comment]
> @smoshiur1237 How are you making sure that you take CAPIRELEASE value set in project-infra?

I am exporting the CAPIRELEASE variable and during the make it will take the value.  It should work same was as we deploy metal3-dev-env.

**Comment by smoshiur1237** [comment]
Need to add a function in the upgrade script to check the machines.

/hold

**Review by Xenwar — APPROVED** [review]

**Pull request merged**
