### PR TITLE
Improve scale-in and node reuse feature tests

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Follow up for improving #633 as per [discussion](https://github.com/metal3-io/metal3-dev-env/pull/633#issuecomment-846845552). Names in the task has been improved to indicate start & end of the each test to make a debugging feature test easier in the future.

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
LGTM. Would you mind to rename the PR tile, and instead mention that this is follow-up in the description?

**Comment by furkatgofurov7** [comment]
/retitle Improve scale-in and node reuse feature tests

**Comment by furkatgofurov7** [comment]
> LGTM. Would you mind to rename the PR tile, and instead mention that this is follow-up in the description?

Yes sure, done.

**Comment by jan-est** [comment]
This looks good to me

**Review by fmuyassarov — COMMENTED** [review]
/approve
We should probably replace all the K8S related shelling with filter plugins that @macaptain suggested.

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
