### PR TITLE
🐛 Downgrade k8s version to v1.23.2 to fix CentOS integration tests

### PR DESCRIPTION
**Pull request by furkatgofurov7**
CentOS integration tests have been failing for some time with:
```
TASK [v1aX_integration_test : Expect 401 from /v1/nodes ednpoint] **************
[1;30mtask path: /home/****/metal3/vm-setup/roles/v1aX_integration_test/tasks/move.yml:187[0m
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "elapsed": 3, "msg": "Status code was -1 and not [401]: Request failed: <urlopen error [Errno 113] No route to host>", "redirected": false, "status": -1, "url": "https://172.22.0.2:6385/v1/nodes"}[
```

and the reason for it was ironicendpoint with IP address 172.22.0.2 is not properly configured and ironic containers failing due to it. 
While debugging it, we got to know the CentOS feature tests were passing (thanks to @Rozzii) both locally and in main jobs, the step where we are failing in normal CentOS integration tests, and the only difference between those tests was the `KUBERNETES_VERSION` used in tests. So, downgrading `KUBERNETES_VERSION` in normal integration tests to v1.23.2 from v1.23.3 looks like helping to pass the failing tests.

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
CI (CentOS tests) looks happy with these changes, although I do not consider this a proper fix, I propose we should take this in to get the CI back on track and continue the investigation, once we know the root cause revert it.

**Review by Rozzii — APPROVED** [review]
LGTM

**Review by dtantsur — APPROVED** [review]
Could we merge this please?

**Pull request merged**
