### PR TITLE
Add release-1.6 branch config for CAPM3 and IPAM

### PR DESCRIPTION
**Pull request by smoshiur1237**
Adding release-1.6 branch configuration for CAPM3 and IPAM

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
lets run some tests here and check if correct versions are used, please run one test for each release branch to make sure nothing is broken

**Comment by smoshiur1237** [comment]
/hold
Need to test with release 1.6 branch after the job addition

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by smoshiur1237** [comment]
/unhold
PR is ready to get merged and pass the release-1.6 test.

**Pull request merged**
