### PR TITLE
Fix iptables missing established and related rule on provisioning

### PR DESCRIPTION
**Pull request by maelk**

### CODE REVIEW

**Comment by hardys** [comment]
any more information on why this was needed?  I'm trying to figure out if we need to also add it to the firewalld tasks cc @stbenjam

**Comment by maelk** [comment]
I have contacted @stbenjam on slack about this. The traffic was not coming back since the rules were allowing only one direction for the traffic

**Comment by stbenjam** [comment]
My EL8 deployments were working fine with the firewalld config that's there.

I will double check but I don't think so, the zone management is a little smarter, it should have that by default.  El7 was also passing with the iptables rules, any idea why it didn't need this?

**Comment by maelk** [comment]
in Ubuntu we have a stricter setup with a DROP policy on the FORWARD chain. if it was an ACCEPT, then we would never see we are missing iptables rules

**Pull request merged**
