### PR TITLE
Move controlplane components upgrade to ubuntu based test

### PR DESCRIPTION
**Pull request by Xenwar**
Previously, the end to end combined test was done using Centos based deployments. 
Since the Ubuntu test already contain most of the components of the end to end test, this PR moves the remaining parts from Centos to the Ubuntu based tests.

### CODE REVIEW

**Comment by Xenwar** [comment]
test-upgrade-features

**Comment by Xenwar** [comment]
This PR is ready to get merged. However, it requires a change on the test framework. hold it until that is done.

**Comment by smoshiur1237** [comment]
Would you please add some description for the PR for clarity? Otherwise looks ok for me.  Lets see the CI run and test framework change.

**Comment by Xenwar** [comment]
> Would you please add some description for the PR for clarity? Otherwise looks ok to me. Lets see the CI run and test framework change.

done

**Comment by kashifest** [comment]
> /test markdownlint
> /test shellcheck

Prow isn't working so these tests wont pass, these will be checked now via travis instead

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
