### PR TITLE
Drop support for RHEL7

### PR DESCRIPTION
**Pull request by hardys**
I don't think this ever worked, because the RDO repo e.g
https://trunk.rdoproject.org/rhel7-master/ doesn't exist,
there are only repos for CentOS7 and RHEL8 atm.

### CODE REVIEW

**Comment by stbenjam** [comment]
Is the RDO repo the only constraint? Can't RHEL use the CentOS one? (And vice versa for CentOS 8)

**Comment by hardys** [comment]
> Is the RDO repo the only constraint? Can't RHEL use the CentOS one? (And vice versa for CentOS 8)

IME mixing RHEL and CentOS repos doesn't work very well - in theory they are compatible but in reality the versions end up subtly different due to the different release cadence.

Also personally I'd prefer to just explicitly support what we're actually testing but open to other suggestions :)

**Pull request merged**
