### PR TITLE
Remove openstackclient container after use

### PR DESCRIPTION
**Pull request by derekhiggins**
Remove old openstackclient containers as they arn't reused

### CODE REVIEW

**Comment by maelk** [comment]
trying again. If it does not work, we can merge manually

**Comment by maelk** [comment]
I removed the v1a2 centos job from the requirements as we do not support v1a2 anymore and it seems broken. Running the v1a3 centos test. if it passes, I will merge manually

**Comment by hardys** [comment]
@maelk any idea how we get tide to merge this, seems like test-centos-integration did succeed, and test-v1a2-centos-integration is no longer needed?

**Comment by maelk** [comment]
I'll merge it manually, the v1a2 test is broken. We could either amend the commit to discard the old tests, or just merge manually

**Pull request merged**
