### PR TITLE
Bump k8s version to v1.28.1

### PR DESCRIPTION
**Pull request by kashifest**
apart from bumping k8s to v1.28.1, this PR also bumps kind node image version and updates renovate config.

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Until https://github.com/Nordix/metal3-dev-tools/pull/691 is merged and images are available in artifactory.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
