### PR TITLE
Bump golang to v1.21.6

### PR DESCRIPTION
**Pull request by kashifest**
as the title says

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm
/hold
In case you need to coordinate with other PRs.

**Comment by dtantsur** [comment]
Note for the future: changing the playbook has zero effect on the CI because 01_prepare_host is not run there (see https://github.com/metal3-io/metal3-dev-env/pull/1226).

**Pull request merged**
