### PR TITLE
Explicitly set IRONIC_FROM_SOURCE default to false

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]

**Comment by elfosardo** [comment]
@dtantsur @lentzi90 @furkatgofurov7 I think we need an explicit /approve in a comment, the approve button won't work

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
Tide config is being updated, which should allow it to merge stuff better. Please don't merge this one manually, tide should handle it soon.

**Pull request merged**
