### PR TITLE
move minikube initialization to step 01

### PR DESCRIPTION
**Pull request by maelk**
this is to optimize CI runs where 01 requirements are baked in

### CODE REVIEW

**Comment by russellb** [comment]
I appreciate the CI optimization.  It seems weird to have this in a script called "install requirements" though.  It seems to fit better with the stuff in the 2nd script.  Or we could rename script 1?

**Comment by maelk** [comment]
For the CI, we are trying to bake in all the expensive download only steps in the image. We do not want to run the 2nd script as it does mostly setup that needs to be validated. Renaming seems then the best option. Maybe something like 01_prepare_host.sh ?

**Comment by russellb** [comment]
`prepare_host` sounds good.

**Comment by maelk** [comment]
@russellb  ok, Updated, and created https://github.com/metal3-io/metal3-io.github.io/pull/92 and https://github.com/Nordix/airship-dev-tools/pull/74

**Pull request merged**
