### PR TITLE
Add BMO release-0.3 branch instead of v0.3.1 tag

### PR DESCRIPTION
**Pull request by kashifest**
adding bmo release-0.3 branch instead of v0.3.1 tag. This will enable testing the BMO release-0.3 branch

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Until BMO release-0.3 branch is created and https://gerrit.nordix.org/c/infra/cicd/+/19773 is merged

**Comment by kashifest** [comment]
> /hold Until BMO release-0.3 branch is created and https://gerrit.nordix.org/c/infra/cicd/+/19773 is merged

BMO release-0.3 branch is in place now

**Comment by kashifest** [comment]
/hold cancel
gerrit PR is merged.

**Comment by kashifest** [comment]
cc @Rozzii @lentzi90 @tuminoid @smoshiur1237

**Review by Rozzii — APPROVED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
