### PR TITLE
Fix ansible firewalld module

### PR DESCRIPTION
**Pull request by kashifest**
Ansbile latest (3.0) has some breaking changes. Changing firewalld to
ansible.posix.firewalld to consume one of those changes.

### CODE REVIEW

**Review by namnx228 — APPROVED** [review]
LGTM

**Comment by fmuyassarov** [comment]
Just to make sure that we don't accidentally breaking the other things...:) 
/test-v1a3-integration
/test-centos-v1a3-integration

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Comment by hardys** [comment]
FYI this is a breaking change on for existing users - we don't upgrade ansible, only install it:

https://github.com/metal3-io/metal3-dev-env/blob/master/centos_install_requirements.sh#L41
https://github.com/metal3-io/metal3-dev-env/blob/master/01_prepare_host.sh#L30

/cc @stbenjam FYI

**Pull request merged**
