### PR TITLE
Remove 'master' reference

### PR DESCRIPTION
**Pull request by kashifest**
This PR removes the reference 'master' from the context and replaces it with proper keyword i.e. controlplane/main etc.

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
Nice!
We need to update update also if we set `NUM_OF MASTER_REPLICAS` for some pipelines. I have seen that we have it at least for the BML pipeline [here](https://github.com/metal3-io/project-infra/blob/master/jenkins/scripts/bare_metal_lab/deploy-lab.yaml#L112)

**Comment by kashifest** [comment]
> Nice! We need to update update also if we set `NUM_OF MASTER_REPLICAS` for some pipelines. I have seen that we have it at least for the BML pipeline [here](https://github.com/metal3-io/project-infra/blob/master/jenkins/scripts/bare_metal_lab/deploy-lab.yaml#L112)

Good point. On it.

**Comment by kashifest** [comment]
> > Nice! We need to update update also if we set `NUM_OF MASTER_REPLICAS` for some pipelines. I have seen that we have it at least for the BML pipeline [here](https://github.com/metal3-io/project-infra/blob/master/jenkins/scripts/bare_metal_lab/deploy-lab.yaml#L112)
> 
> Good point. On it.

@lentzi90 here it is https://github.com/metal3-io/project-infra/pull/296

**Pull request merged**
