### PR TITLE
Fix readme test paths

### PR DESCRIPTION
**Pull request by mboukhalfa**
After isolating the test files in the PR #1026 some paths in the readme have to be updated accordingly

### CODE REVIEW

**Review by furkatgofurov7 — CHANGES_REQUESTED** [review]
Can you please update the other README file for feature tests in the same PR? 
https://github.com/metal3-io/metal3-dev-env/blob/main/tests/feature_tests/README.md

**Comment by mboukhalfa** [comment]
> Can you please update the other README file for feature tests in the same PR? https://github.com/metal3-io/metal3-dev-env/blob/main/tests/feature_tests/README.md

I do not see somthing needs change in feature tests readme

**Comment by furkatgofurov7** [comment]
> I do not see somthing needs change in feature tests readme

alright, that folder was moved as is, sorry I forgot that. 

/approve

**Comment by mboukhalfa** [comment]
> /test-centos-integration-release-0-5

I think we have to push a no-edit commit to remove the failed test ?

**Pull request merged**
