### PR TITLE
Uplift kind node image and kind binary

### PR DESCRIPTION
**Pull request by kashifest**
This PR uplifts the following:

- kind binary to v0.11.0
- kind node image to v1.21.1

### CODE REVIEW

**Comment by fmuyassarov** [comment]
We also need to update https://github.com/Nordix/airship-dev-tools/blob/0ef5eb98f74c9c1db97d500ca6d76af18ce218a3/ci/scripts/image_scripts/source_cluster_container_images.sh#L13 with the same version.

**Comment by kashifest** [comment]
The reason of the failure is somewhat related to kubernetes version 1.21.0 as discussed in the issue here https://github.com/kubernetes-sigs/kind/issues/2188 . The solution seems to be in kind master branch now but we have to wait for a release to consume that.

**Comment by fmuyassarov** [comment]
> ems to be in kind master bra

@kashifest  we could build the kind image from master ourselves for now until they actually release the official one

**Comment by kashifest** [comment]
> > ems to be in kind master bra
> 
> @kashifest we could build the kind image from master ourselves for now until they actually release the official one

That and build the binary also. Shall we do that or shall we wait?

**Comment by fmuyassarov** [comment]
> > > ems to be in kind master bra
> > 
> > 
> > @kashifest we could build the kind image from master ourselves for now until they actually release the official one
> 
> That and build the binary also. Shall we do that or shall we wait?

Do we know when the Kind community is planning to have a new release ? I think we can anyways build it ourselves until they release the official one soon or later.

**Comment by kashifest** [comment]
> > > > ems to be in kind master bra
> > > 
> > > 
> > > @kashifest we could build the kind image from master ourselves for now until they actually release the official one
> > 
> > 
> > That and build the binary also. Shall we do that or shall we wait?
> 
> Do we know when the Kind community is planning to have a new release ? I think we can anyways build it ourselves until they release the official one soon or later.

my Bad, we need the binary only because this PR is already using the new image :)

**Comment by fmuyassarov** [comment]
@kashifest  a new release of Kind just came out, let's use that.

**Comment by kashifest** [comment]
> @kashifest a new release of Kind just came out, let's use that.

Indeed. Changed the PR. PTAL @fmuyassarov

**Comment by smoshiur1237** [comment]
All the tests are successful and I don't see any issue to give lgtm.
/lgtm

**Pull request merged**
