### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by jan-est**
Operator-sdk installation instructions added

### CODE REVIEW

**Comment by russellb** [comment]
Thanks for the patch!

Would you mind updating the commit message to describe a bit more about the change?  It could be something like:

`README.md: Note that operator-sdk is required by baremetal-operator."

**Comment by jan-est** [comment]
Sure!

**Comment by jan-est** [comment]
Hi @russellb I update the commit message.

**Comment by russellb** [comment]
Thanks again

**Pull request merged**
