### PR TITLE
Test CAPM3 main branch with CAPI v1.7.0-beta.0

### PR DESCRIPTION
**Pull request by kashifest**
This PR allows testing main branch tests with CAPI v1.7.0-beta.0

### CODE REVIEW

**Comment by kashifest** [comment]
/override test-ubuntu-e2e-integration-main 
This PR wont pass the e2e test until https://github.com/metal3-io/cluster-api-provider-metal3/pull/1530 lands. But we have tested that it works in e2e feature test with this branch here https://jenkins.nordix.org/job/metal3_capm3_main_e2e_feature_test_ubuntu/111/ and other e2e integration tests and upgrade tests as well

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
