### PR TITLE
Allow using redfish-virtualmedia as protocol type for BMC's

### PR DESCRIPTION
**Pull request by stbenjam**
This adds support for redfish-virtualmedia as a BMC type.

### CODE REVIEW

**Comment by maelk** [comment]
The CI was unstable for Ubuntu today, retriggering
/test-integration

**Comment by maelk** [comment]
Let's see if this one passes, but it starts to look less like CI instability, with so many runs.

**Comment by maelk** [comment]
If this one does not pass, we should probably merge manually

**Comment by stbenjam** [comment]
Looks why we don't have that plugin.

@maelk Are you ok if we merge this one manually? Or do you want to test again one more time? Integration tests did pass on https://github.com/metal3-io/metal3-dev-env/pull/362

**Comment by stbenjam** [comment]
/test-integration

:crossed_fingers:

**Pull request merged**
