### PR TITLE
Add IRONIC_AUTH_STRATEGY

### PR DESCRIPTION
**Pull request by iurygregory**
This commit adds the IRONIC_AUTH_STRATEGY env var default to `noauth`.
This will help the [PR for the BMO](https://github.com/metal3-io/baremetal-operator/pull/601) to support `http_basic` since we will
require a value for `IRONIC_AUTH_STRATEGY`.

### CODE REVIEW

**Comment by iurygregory** [comment]
> Does it need to be added [here](https://github.com/metal3-io/metal3-dev-env/blob/052c0add50dba9ec83f4a3012c1c19bfe9bc1d40/03_launch_mgmt_cluster.sh#L116) too?

@fmuyassarov I've added to 03_launch_mgmt_cluster.sh https://github.com/metal3-io/metal3-dev-env/pull/389/files#diff-ee6766d0e2c6e5dfa4669f52720ee0c1

**Comment by iurygregory** [comment]
the unit tests are failling since I'm requiring the variable, see https://prow.apps.ci.metal3.io/view/gcs/metal3-prow-artifacts/pr-logs/pull/metal3-io_baremetal-operator/601/unit/1285687195830587392 , and since the default will be `noauth` there will be no problem in adding the env var.

**Comment by fmuyassarov** [comment]
> > Does it need to be added [here](https://github.com/metal3-io/metal3-dev-env/blob/052c0add50dba9ec83f4a3012c1c19bfe9bc1d40/03_launch_mgmt_cluster.sh#L116) too?
> 
> @fmuyassarov I've added to 03_launch_mgmt_cluster.sh https://github.com/metal3-io/metal3-dev-env/pull/389/files#diff-ee6766d0e2c6e5dfa4669f52720ee0c1, I assume it will be necessary so BMO won't complain that the variable is missing

My bad. Sorry, missed that.

**Pull request merged**
