### PR TITLE
Removed ansible-based feature tests.

### PR DESCRIPTION
**Pull request by huutomerkki**
Removed all targets, rules and files related to them, excluding those used in the integration tests.

### CODE REVIEW

**Comment by mboukhalfa** [comment]
verifying that ubuntu ansible test also passing 
/test-ubuntu-integration-main

**Comment by mboukhalfa** [comment]
/lgtm
Great job ! Finally Dev-Env lighter and simpler  No feature tests no upgrade ☺️ 
/assign @lentzi90

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
