### PR TITLE
Update image/*location with upgraded k8s version notes

### PR DESCRIPTION
**Pull request by furkatgofurov7**

### CODE REVIEW

**Comment by namnx228** [comment]
Why do we hold this PR?

**Comment by furkatgofurov7** [comment]
> Why do we hold this PR?

Hi @namnx228! I did not want this to go in before the other patch that can have a conflict with this change, but that is okay now, no reason for holding, forgot to unhold it, thanks!

/unhold

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
