### PR TITLE
Update k8sversion to 1.18.8

### PR DESCRIPTION
**Pull request by kashifest**
This PR Updates k8s version to 1.18.8 to avoid mismatch in kubelet and kubectl versions since in node image we already use k8s version 1.18.8

### CODE REVIEW

**Comment by Xenwar** [comment]
A description in the commit would make this PR easy to understand in the future.

**Comment by kashifest** [comment]
> A description in the commit would make this PR easy to understand in the future.

Commit description is there, you mean PR I guess, updating it

**Review by Jaakko-Os — CHANGES_REQUESTED** [review]
This change will impact the k8s version upgrade tests.
It should be verified within this PR that at least one k8s version upgrade test is successful.

**Comment by kashifest** [comment]
> This change will impact the k8s version upgrade tests.
> It should be verified within this PR that at least one k8s version upgrade test is successful.

That is something that the upgrade tests should take care of since the environment is changing.  I am not going to change upgrade tests in this PR.

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
Looks good to me!

**Review by maelk — APPROVED** [review]

**Pull request merged**
