### PR TITLE
Small updates for lint-tests to succeed

### PR DESCRIPTION
**Pull request by kashifest**
Minor Changes of the following files for lint tests to succeed
1. README.md
2. lib/logging.sh

### CODE REVIEW

**Comment by russellb** [comment]
Can you clarify what lint command(s) you're running that led to these changes?

**Comment by kashifest** [comment]
> Can you clarify what lint command(s) you're running that led to these changes?

@russellb I ran the /lint from the CI

**Comment by kashifest** [comment]
> Can you clarify what lint command(s) you're running that led to these changes?
@russellb sorry, the /lint command only works in Nordix's internal pull requests. To answer your question, the errors were thrown while the doing ```lint-md``` and ```lint-shell```

**Comment by russellb** [comment]
OK. If you can share what tools are being run then we can run them here. I’d like to set up a CI job to avoid regression.

**Comment by kashifest** [comment]
> OK. If you can share what tools are being run then we can run them here. I’d like to set up a CI job to avoid regression.

For lint-shell, its koalaman/shellcheck-alpine:v0.7.0 docker image and for lint-md its mdl -ruby

**Comment by russellb** [comment]
Ok. We’re running shellcheck but the stable tag. I’ll take a closer look

**Comment by russellb** [comment]
The stable tag looks to be the same as 0.7.0, so not sure why we aren't seeing the same warning.  https://hub.docker.com/r/koalaman/shellcheck/tags

**Comment by russellb** [comment]
Can you send me a link to what you're referring to by "mdl -ruby"?

**Comment by kashifest** [comment]
> The stable tag looks to be the same as 0.7.0, so not sure why we aren't seeing the same warning. https://hub.docker.com/r/koalaman/shellcheck/tags

Thats strange. I have no idea. Attached is the output of console of the linter test which failed  and for which I made the change in this PR: 

[linter.txt](https://github.com/metal3-io/metal3-dev-env/files/3708517/linter.txt)

**Comment by kashifest** [comment]
> Can you send me a link to what you're referring to by "mdl -ruby"?

https://github.com/markdownlint/markdownlint

**Comment by russellb** [comment]
> > The stable tag looks to be the same as 0.7.0, so not sure why we aren't seeing the same warning. https://hub.docker.com/r/koalaman/shellcheck/tags
> 
> Thats strange. I have no idea. Attached is the output of console of the linter test which failed and for which I made the change in this PR:
> 
> [linter.txt](https://github.com/metal3-io/metal3-dev-env/files/3708517/linter.txt)

Thanks.  It's running `	sh /mnt/scripts/shell-linter.sh` -- what is in that script?  We are probably using different arguments to shellcheck.

**Comment by russellb** [comment]
I'm going to merge this and follow up with a new markdownlint CI job.  I'd like to fix our shellcheck job still, too, so let's keep that thread going.

/approve

**Comment by kashifest** [comment]
> > > The stable tag looks to be the same as 0.7.0, so not sure why we aren't seeing the same warning. https://hub.docker.com/r/koalaman/shellcheck/tags
> > 
> > 
> > Thats strange. I have no idea. Attached is the output of console of the linter test which failed and for which I made the change in this PR:
> > [linter.txt](https://github.com/metal3-io/metal3-dev-env/files/3708517/linter.txt)
> 
> Thanks. It's running `	sh /mnt/scripts/shell-linter.sh` -- what is in that script? We are probably using different arguments to shellcheck.

I will check tomorrow and get back to you

**Pull request merged**
