### PR TITLE
Remove extra '/' from IMAGE_LOCATION

### PR DESCRIPTION
**Pull request by kashifest**
The extra / at the end of IMAGE_LOCATION var is creating wrong URL such as this https://artifactory.nordix.org/artifactory/airship/images/k8s_v1.23.3//UBUNTU_20.04_NODE_IMAGE_K8S_v1.23.3.qcow2

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
> The extra / at the end of IMAGE_LOCATION var is creating wrong URL such as this https://artifactory.nordix.org/artifactory/airship/images/k8s_v1.23.3//UBUNTU_20.04_NODE_IMAGE_K8S_v1.23.3.qcow2

@kashifest how this was working so far, this was still valid to download the images, even it has extra `/`?

**Comment by kashifest** [comment]
> > The extra / at the end of IMAGE_LOCATION var is creating wrong URL such as this https://artifactory.nordix.org/artifactory/airship/images/k8s_v1.23.3//UBUNTU_20.04_NODE_IMAGE_K8S_v1.23.3.qcow2
> 
> @kashifest how this was working so far, this was still valid to download the images, even it has extra `/`?

Yes it works with that extra /, but the URL is incorrect anyhow. So its better to remove this.

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Pull request merged**
