### PR TITLE
Uplift ubuntu to 22.04

### PR DESCRIPTION
**Pull request by mboukhalfa**
depends on https://github.com/metal3-io/cluster-api-provider-metal3/pull/712

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/hold 
should merged together with https://github.com/metal3-io/cluster-api-provider-metal3/pull/712

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
Thanks @mboukhalfa 

/approve

**Pull request merged**
