### PR TITLE
add lib/debug.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Add debug library that can print out variables and track their values to help debug various problems in dev-env more efficiently.

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-ubuntu-e2e-integration-main  
/test-centos-e2e-integration-main

/test-ubuntu-integration-release-1-3
/test-centos-integration-release-1-3

/test-ubuntu-integration-main
/test-centos-integration-main

Let's see what all of these tests are made of.

**Review by lentzi90 — COMMENTED** [review]
Nice!
/approve

**Comment by kashifest** [comment]
I dont see it being called from anywhere? So whats the plan?

**Comment by tuminoid** [comment]
> I dont see it being called from anywhere? So whats the plan?

It is added as a library so it can be activated to aid in debugging. It is not actively called anywhere by default.

**Comment by Sunnatillo** [comment]
Great job @tuminoid. Would it be better if we rename file name `debug_vars.sh` for specifying its usage? 
Otherwise LGTM.

**Comment by kashifest** [comment]
/lgtm

> > Great job @tuminoid. Would it be better if we rename file name `debug_vars.sh` for specifying its usage? Otherwise LGTM.
> 
> It could be, but I doubt we will introduce `debug_something_else.sh` there, but rather add to the same `debug.sh` whatever debug funcs we come up with, so IMO this is better.

Agree

**Pull request merged**
