### PR TITLE
remove release-1.6 support

### PR DESCRIPTION
**Pull request by tuminoid**
Remove release-1.6 support.

### CODE REVIEW

**Comment by tuminoid** [comment]
All dev-env prs need to wait https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164 to be merged to restore main.

**Comment by tuminoid** [comment]
/retest
Unrelated failure.

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-release-1-9 metal3-centos-e2e-integration-test-release-1-8
CI for 1.9 is broken, and 1.8 is wrongly there (soon fixed).

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
