### PR TITLE
Remove ironic-log and inspector-log in move

### PR DESCRIPTION
**Pull request by kashifest**
Remove newly created ironic-log and inspector-log containers from source cluster during pivoting.

### CODE REVIEW

**Review by fmuyassarov — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
Looks okay to me, don't we need to include them in the feature test [cleanup script](https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/cleanup_env.sh#L21) as well?

**Comment by fmuyassarov** [comment]
> Looks okay to me, don't we need to include them in the feature test [cleanup script](https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/cleanup_env.sh#L21) as well?

I think the idea was to move those containers deletion into a single place, to Baremetal Operator repo I guess @kashifest ?

**Comment by kashifest** [comment]
> > Looks okay to me, don't we need to include them in the feature test [cleanup script](https://github.com/metal3-io/metal3-dev-env/blob/master/scripts/feature_tests/cleanup_env.sh#L21) as well?
> 
> I think the idea was to move those containers deletion into a single place, to Baremetal Operator repo I guess @kashifest ?

Yes. That requires changes in BMO and m3-dev-env. I ll take it up in separate PRs. For now, lets keep it synced.
@furkatgofurov7 I have addressed your comment.

/test-integration
/test-centos-integration
/test-features

**Comment by smoshiur1237** [comment]
Looks good to me

**Pull request merged**
