### PR TITLE
Silence fetch logs and fetch manifests

### PR DESCRIPTION
**Pull request by Sunnatillo**
Silence fetch logs and fetch manifests as they are too noise in the jenkins logs, which makes  debugging difficult.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
While this might hide some issues sometimes, I agree it is annoying that the log collection is often most of the log output.

/approve

**Comment by Sunnatillo** [comment]
/override metal3-centos-e2e-integration-test-release-1-7

one test would be enough for this small change.

**Review by Rozzii — COMMENTED** [review]
/lgtm
I don't really mind the logs but I don't have strong opinion on this.

**Pull request merged**
