### PR TITLE
Move clusterctl installation to support older version of releases

### PR DESCRIPTION
**Pull request by smoshiur1237**
Currently we are not using 01 script for our CI run which creates an issue with the version of clusterctl. Moving the installation of clusterctl before cluster init will solve the issue.

### CODE REVIEW

**Comment by Sunnatillo** [comment]
/test-ubuntu-e2e-integration-release-1.2

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
