### PR TITLE
Stop using Travis for mandatory CI jobs

### PR DESCRIPTION
**Pull request by fmuyassarov**
As our Prow cluster is back on track, we should stop using Travis for running markdown & shellcheck in this repo.

### CODE REVIEW

**Comment by kashifest** [comment]
Isn't it possible to keep this file but just disable travis CI in repo configs ?

**Comment by fmuyassarov** [comment]
> Isn't it possible to keep this file but just disable travis CI in repo configs ?

Probably disabling it from Github status check would suffice in this case, or will it be still running behind?

**Comment by kashifest** [comment]
This is not needed anymore since we have disabled travis from the settings

**Comment by fmuyassarov** [comment]
We have disabled Travis instead of deleting the configuration file.
/close

**Pull request closed without merging**
