### PR TITLE
[WIP] control kubeconfig to point to target or management cluster

### PR DESCRIPTION
**Pull request by Jaakko-Os**
Point to management cluster by default. On need basis the kubeconfig is set to point to target cluster.

### CODE REVIEW

**Comment by Xenwar** [comment]
Could this be a duplicate of https://github.com/metal3-io/metal3-dev-env/pull/500 ?

**Comment by Jaakko-Os** [comment]
> Could this be a duplicate of #500 ?

Most likely. My understanding was that our work group creates WIP PRs when testing work proceeds. This is just a way to share my contribution.

**Comment by Jaakko-Os** [comment]
Content merged in other PRs

**Pull request closed without merging**
