### PR TITLE
Remove support for Ubuntu 18 Bionic

### PR DESCRIPTION
**Pull request by elfosardo**
It's not tested anymore and it has reached end of standard support a year ago.

### CODE REVIEW

**Comment by elfosardo** [comment]
let's wait for https://github.com/metal3-io/metal3-dev-env/pull/1428 to merge first

**Comment by tuminoid** [comment]
/test metal3-dev-env-integration-test-ubuntu-main 

Not that this actually tests anything, except very basic syntax, but let's run it anyways.

**Comment by tuminoid** [comment]
> let's wait for #1428 to merge first

Its merged.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by dtantsur — APPROVED** [review]

**Review by Rozzii — COMMENTED** [review]
/approve

**Review by Rozzii — COMMENTED** [review]
/approve

**Pull request merged**
