### PR TITLE
Fix BMOPATH in ansible

### PR DESCRIPTION
**Pull request by kashifest**
Fix BMOPATH in ansible

### CODE REVIEW

**Review by fmuyassarov — APPROVED** [review]

**Comment by fmuyassarov** [comment]
I re-triggered the Centos job because it failed for some infra related issue.
```

Copying blob sha256:751620502a7a2905067c2f32d4982fb9b310b9808670ce82c0e2b40f5307a3ee
  read tcp 10.100.10.127:34752->65.9.43.65:443: read: connection reset by peer
Error: error pulling image "quay.io/metal3-io/sushy-tools": unable to pull quay.io/metal3-io/sushy-tools: unable to pull image: Error writing blob: error storing blob to file "/var/tmp/storage245080681/4": read tcp 10.100.10.127:34752->65.9.43.65:443: read: connection reset by peer
make: *** [Makefile:4: install_requirements] Error 125

```

**Review by maelk — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
Hmm, I was thinking BMOPATH needs to be changed in couple of places in move.yml but exporting it in lib/common turned out to be a better approach.

/lgtm

**Pull request merged**
