### PR TITLE
Remove v1alpha1 scripts

### PR DESCRIPTION
**Pull request by fmuyassarov**
Remove unused:

- `/scripts/v1alpha1/`
- `provision_host.sh`
- `deprovision_host.sh`

### CODE REVIEW

**Comment by Jaakko-Os** [comment]
v1alpha1 directory is deleted here, right?

**Comment by fmuyassarov** [comment]
> v1alpha1 directory is deleted here, right?
Yes

**Comment by fmuyassarov** [comment]
Seems quay issue isn't fixed yet

**Pull request merged**
