### PR TITLE
Add retry loop for deployment verification and test script

### PR DESCRIPTION
**Pull request by maelk**
- add a retry loop, waiting for the setup to complete (for example for the baremetal hosts to get ready etc.)
- add a test script that provisions two machines 
- some shell linting fixes in lib/common.sh

Issue #39

### CODE REVIEW

**Comment by russellb** [comment]
I tried this and it seemed to work.  Could we change it so it doesn't like "FAIL" while waiting for something that we know will take a while?  Can it just indicating that it's still waiting, and not say FAIL unless it's giving up and considering it a failure?

**Comment by maelk** [comment]
@russellb Thank you for the comment. I have now refactored the code. It waits before either succeeding or failing, but does not say FAIL in between anymore

**Comment by russellb** [comment]
Thanks.  I tried this again today.  The output looks much better.  I did get two failures:

```
FAIL - centos-1 baremetal host in correct state : provisioned
...
FAIL - centos-1 baremetal host reachable by ssh
```

and that machine was provisioned successfully, so maybe the timeout just needs to be increased a bit more.

**Comment by maelk** [comment]
@russellb Thank you. I have increased the number of retries, the timeout will happen after 20 minutes. This can be configured with environment variables, so I added those in config_example.sh

**Comment by russellb** [comment]
OK - tested again and this is working for me. My only minor suggestion is that it would be nice to know what task is being waited on.  Right now you don't find out until it's done.

Thanks!

**Pull request merged**
