### PR TITLE
Add namespace directory in manifest collection

### PR DESCRIPTION
**Pull request by smoshiur1237**
There is a possibility to miss same kinds of manifest in different namespace. So this PR will add the namespace directory in manifest collection to gather all the manifests which will improve debugging capability.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by smoshiur1237** [comment]
Manifest can be checked here :
https://jenkins.nordix.org/view/Metal3/job/metal3-dev-env-integration-test-ubuntu-main/37/

**Review by mboukhalfa — APPROVED** [review]

**Pull request merged**
