### PR TITLE
Bump golang to v1.22.3

### PR DESCRIPTION
**Pull request by kashifest**
This PR bumps golang to v1.22.3 for dev-env based tests. This is a minor version upgrade of go from v1.21.x to v1.22.x
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
/override metal3-centos-e2e-integration-test-release-1-7 
It is failing since last week for some unrelated reason

**Pull request merged**
