### PR TITLE
Bump minikube to v1.31.2

### PR DESCRIPTION
**Pull request by kashifest**
As the title says. Also trying to test if it solves the issue reported in  https://github.com/metal3-io/metal3-dev-env/issues/1264 by removing the extra libvirtd restart. Upstream issue https://github.com/kubernetes/minikube/issues/16975

### CODE REVIEW

**Review by Sunnatillo — APPROVED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

Do we need to run any extra tests to verify that it solves the hanging issue?
/hold

**Comment by Sunnatillo** [comment]
> /approve
> 
> Do we need to run any extra tests to verify that it solves the hanging issue? /hold

as I remember it failed every time without restarting libvirt line. So it should be fine now.

**Comment by kashifest** [comment]
> /approve
> 
> Do we need to run any extra tests to verify that it solves the hanging issue? /hold

I ran all the centos integration tests. Seems not to occur. Do you suggest any other tests ?

**Comment by lentzi90** [comment]
> > /approve
> > Do we need to run any extra tests to verify that it solves the hanging issue? /hold
> 
> if I remember correctly, it failed every time without restarting libvirt. So it should be fine now.

Good, then we should be fine :slightly_smiling_face: 

/hold cancel

**Review by tuminoid — COMMENTED** [review]
LGTM

Did you use the new helper script for the digests?

**Pull request merged**
