### PR TITLE
Replace master branch reference with main

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> /hold

As per discussion on slack: https://estech-group.slack.com/archives/GL5H2U2FM/p1646741474528359?thread_ts=1646737846.261359&cid=GL5H2U2FM
@kashifest feel free to unhold if you think otherwise!

**Comment by kashifest** [comment]
/hold
Until default branch is main

**Comment by kashifest** [comment]
/hold cancel
Default branch is now main.

**Pull request merged**
