### PR TITLE
Remove downgrading NetworkManager

### PR DESCRIPTION
**Pull request by Sunnatillo**
In v1.41.7 version of NM is issue of failure when creating a bridge is gone

### CODE REVIEW

**Comment by Sunnatillo** [comment]
tested [here](https://jenkins.nordix.org/job/metal3_dev_tools_integration_test_centos/166/consoleFull)

**Comment by Sunnatillo** [comment]
hold until dev tools gets[ PR merged ](https://github.com/Nordix/metal3-dev-tools/pull/643)

**Comment by Sunnatillo** [comment]
/hold
until dev tools gets PR merged

**Comment by Sunnatillo** [comment]
/test-centos-integration-release-1-3
/test-ubuntu-integration-main
//test-features-centos

**Comment by Sunnatillo** [comment]
/test-features-centos
//test-centos-e2e-main

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Pull request merged**
