### PR TITLE
Add a variable for mariadb-image

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Comment by fmuyassarov** [comment]
Probably I'm missing some context, but ]what's the use of this variable? Are you expecting to have a follow up PR to decouple mariadb container from ironic when running outside of k8s cluster, similar to https://github.com/metal3-io/baremetal-operator/blob/332a5ca6ccce2167236cd8ba7d92d834c2057208/ironic-deployment/ironic/ironic.yaml#L52 ?

**Comment by dtantsur** [comment]
@fmuyassarov all variables ending with `_IMAGE` are automagically processed to cache local images: https://github.com/metal3-io/metal3-dev-env/blob/master/02_configure_host.sh#L139 https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L89

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
