### PR TITLE
Bump sushy-tools version

### PR DESCRIPTION
**Pull request by bfournie**
Bump sushy-tools version to 0.17.0 to pick up BIOS attribute registry support for testing.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Hi @bfournie , we have migrated vbmc and sushy-tools Dockerfiles to [Ironic-image repo](https://github.com/metal3-io/ironic-image/tree/master/resources). Can you please open this PR towards ironic-image repository ? Sorry that we forgot to clean up it here, I will do it asap.

**Comment by bfournie** [comment]
> Hi @bfournie , we have migrated vbmc and sushy-tools Dockerfiles to [Ironic-image repo](https://github.com/metal3-io/ironic-image/tree/master/resources). Can you please open this PR towards ironic-image repository ? Sorry that we forgot to clean up it here, I will do it asap.

Thank you. I've opened https://github.com/metal3-io/ironic-image/pull/285 and will close this one.

**Pull request closed without merging**
