### PR TITLE
Add Missing IP in Metal3 Data Template for Centos

### PR DESCRIPTION
**Pull request by kashifest**
This PR adds missing provisioning IP in Metal3 Data Template for the Centos target nodes.

### CODE REVIEW

**Review by maelk — CHANGES_REQUESTED** [review]
This would make Ubuntu nodes have the same IP address on two different interfaces. You should maybe rather set up the bridge on CentOS, so that it can also be used to test features.

**Comment by kashifest** [comment]
@maelk at-least this kinda explains the delay incase of Centos v1a4, it took only an hour and 5 minutes. https://jenkins.nordix.org/view/Airship/job/airship_metal3io_metal3_dev_env_v1a4_integration_test_centos/153/

**Comment by kashifest** [comment]
This is a quick fix for CI, I will add the bridge for Centos on a separate PR
/hold cancel
/test-centos-integration
/test-integration
/assign @maelk 
/cc @fmuyassarov

**Review by maelk — APPROVED** [review]

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
