### PR TITLE
🐛 Workaround to fix github api limit for capi release

### PR DESCRIPTION
**Pull request by mboukhalfa**
A workaround to unlock the CI by increasing the api response limit

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
cc

**Comment by kashifest** [comment]
It should go in now. There was another PR in merge queue

**Pull request merged**
