### PR TITLE
Pin cert manager to v1.10.0 in the CI

### PR DESCRIPTION
**Pull request by furkatgofurov7**
/hold

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by lentzi90 — COMMENTED** [review]
/lgtm
I think we may need a PR also in CAPM3 if we want to use it for all e2e tests, or maybe it is using the same config file?

**Comment by furkatgofurov7** [comment]
> I think we may need a PR also in CAPM3 if we want to use it for all e2e tests, or maybe it is using the same config file?

e2e upgrade tests use an older version of it on purpose AFAIR https://github.com/metal3-io/cluster-api-provider-metal3/pull/755/files#r997285628 otherwise bootstrapping dev env when starting normal e2e should use the latest. 
However, other files, i.e Tiltfile, and scripts under hack can be updated.

**Pull request merged**
