### PR TITLE
Point CAPM3RELEASE to v1.5.99 for release-1.5 branch

### PR DESCRIPTION
**Pull request by kashifest**
This is to sync with [CAPM3 e2e settings](https://github.com/metal3-io/cluster-api-provider-metal3/blob/8fb524c4db32dfe5e37ae82704851f31b51d1302/test/e2e/config/e2e_conf.yaml#L98)

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

This will fix the 1.5 e2e.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
