### PR TITLE
Disable support for no authentication for Ironic

### PR DESCRIPTION
**Pull request by dtantsur**
There is little reason to run without authentication. Dropping it will
simplify logic here, in ironic-image and in BMO deployment.

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
Until default branch is main

**Comment by kashifest** [comment]
/hold cancel
Default branch is now main. Remember to rebase your PR on top of main branch.

**Comment by mboukhalfa** [comment]
/assign @mboukhalfa 
LGTM, I will review again When rebased

**Pull request closed without merging**
