### PR TITLE
Add image checksum type and format for target cluster

### PR DESCRIPTION
**Pull request by maelk**
This sets the options added in https://github.com/metal3-io/cluster-api-provider-metal3/pull/78

### CODE REVIEW

**Comment by maelk** [comment]
/hold cancel
adding checksumType in CAPM3

**Comment by fmuyassarov** [comment]
Why do you need `IMAGE_FORMAT` ?

**Comment by maelk** [comment]
That's coming next, stay tuned ;)

**Comment by maelk** [comment]
joke aside, it's coming from this PR https://github.com/metal3-io/cluster-api-provider-metal3/pull/78 , but needed to be set beforehand in emtal3-dev-env for the tests to pass (clusterctl complains otherwise).

**Pull request merged**
