### PR TITLE
Uplift k8s to 1.21.2

### PR DESCRIPTION
**Pull request by kashifest**
Feature test and Upgrade will test k8s version upgrade from 1.21.1 -> 1.21.2
This PR also reverts Centos stream images since there are issues. We fix the bug regarding centos node image and point it to Centos8.3

### CODE REVIEW

**Comment by kashifest** [comment]
/hold 
until [images](https://github.com/Nordix/airship-dev-tools/pull/324) are created.

**Review by lentzi90 — APPROVED** [review]

**Review by macaptain — APPROVED** [review]

**Review by fmuyassarov — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
