### PR TITLE
K8s version upgrade from 1.20.0 to 1.20.2 for upgrade workflow.

### PR DESCRIPTION
**Pull request by smoshiur1237**
Kubernetes version change for upgrade workflow. Also added a fix for unqualified image error: ImageInspectError issue.

### CODE REVIEW

**Review by fmuyassarov — COMMENTED** [review]
LGTM

**Comment by namnx228** [comment]
lgtm

**Review by kashifest — APPROVED** [review]
/test-upgrade-features

**Review by kashifest — COMMENTED** [review]
The kubernetes version is now by default 1.20.2, so your code will not work since 1.20.2 is not < than 1.20.2

**Comment by smoshiur1237** [comment]
> The kubernetes version is now by default 1.20.2, so your code will not work since 1.20.2 is not < than 1.20.2

Yes you are right. I don't have any option to upgrade from 1.20.2 to 1.20.3. We need to wait for newer version of the kubernetes.

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
