### PR TITLE
Changing defaults from md5 to sha256

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Changing defaults from md5 to sha256 to fix capm3 pr: https://github.com/metal3-io/cluster-api-provider-metal3/pull/975

### CODE REVIEW

**Review by kashifest — DISMISSED** [review]

**Comment by adilGhaffarDev** [comment]
/hold 
md5sum file is in the host image and it is not being replaced by sha256sum. That needs to be fixed in this PR first.

**Pull request merged**
