### PR TITLE
Switch sushy-tools to bind to "::"

### PR DESCRIPTION
**Pull request by derekhiggins**
To allow the emulator to work with IPv6

### CODE REVIEW

**Comment by russellb** [comment]
/approve

lgtm assuming integration tests pass

**Comment by derekhiggins** [comment]
/test-v1a2-centos-integration


```
Error: Error downloading packages:
  Curl error (28): Timeout was reached for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=genclo [Connection timed out after 30000 milliseconds]
```

**Comment by maelk** [comment]
It hit this error again. Let's try again in a couple of hours

**Comment by maelk** [comment]
all PRs are now stuck with the hosts not coming back to ready state in CentOS v1a2 tests. we need to look into this.

**Comment by maelk** [comment]
I removed the v1a2 centos job from the requirements as we do not support v1a2 anymore and it seems broken. Running the v1a3 centos test. if it passes, I will merge manually

**Pull request merged**
