### PR TITLE
Debug no-metal3cluster issue without pivot

### PR DESCRIPTION
**Pull request by mboukhalfa**
ref https://github.com/metal3-io/metal3-dev-env/pull/1435#issuecomment-2200320372

### CODE REVIEW

**Comment by tuminoid** [comment]
> /override metal3-dev-env-integration-test-ubuntu-main

Curious: why bother overriding in a test PR that is not going to be merged?

**Comment by mboukhalfa** [comment]
> Curious: why bother overriding in a test PR that is not going to be merged?

I just wanted to stop it not sure of the proper way was to go to jenkins and stop it instead

**Pull request closed without merging**
