### PR TITLE
Add pivot and repivot in normal CI tests

### PR DESCRIPTION
**Pull request by kashifest**
Add pivot and repivot in normal CI tests

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
Why not to run feature test since it is touching it?

**Comment by kashifest** [comment]
> Why not to run feature test since it is touching it?

Is it?

**Comment by furkatgofurov7** [comment]
> > Why not to run feature test since it is touching it?
> 
> Is it?

Idk, I was fooled by PR title maybe?

**Review by fmuyassarov — APPROVED** [review]

**Comment by maelk** [comment]
well itis definitely modifying a part of the code that is used for feature test. but that would now also be tested by the integration tests, so I think it is ok not to run the feature tests

**Review by maelk — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
> well itis definitely modifying a part of the code that is used for feature test. but that would now also be tested by the integration tests, so I think it is ok not to run the feature tests

Yes. Since the repivot was tested in integration, I also think it is ok not to test feature since it didn't touch anything else regarding feature test.

**Pull request merged**
