### PR TITLE
Bump ansible to latest

### PR DESCRIPTION
**Pull request by fmuyassarov**
Fixes https://github.com/metal3-io/metal3-dev-env/issues/353

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/test-integration
test-centos-integration

**Review by maelk — APPROVED** [review]
so the issue with the user was a glitch in a specific version ?

**Comment by fmuyassarov** [comment]
> so the issue with the user was a glitch in a specific version ?

Yes, it seems so. Latest version is 2.9.13 and apparently we don't have that problem anymore.

**Pull request merged**
