### PR TITLE
Clean when deleting minikube

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR adds options `--all --purge ` to `minikube delete` to delete all profiles and the '.minikube' folder. 

This will avoid any potential issue when retrying to create minikube such as : `Message='operation failed: network 'mk-minikube' already exists with uuid c79ec658-7a5d-4453-9836-0dfe2e62188b'` seen [here](https://jenkins.nordix.org/view/Airship/job/airship_master_feature_tests_centos/458/consoleFull).

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Same issue here as commented in https://github.com/metal3-io/metal3-dev-env/pull/751#issuecomment-890069588

**Comment by mboukhalfa** [comment]
> Same issue here as commented in [#751 (comment)](https://github.com/metal3-io/metal3-dev-env/pull/751#issuecomment-890069588)

Yes this issue is not related to the PRs I have tested the master with v1lpha5 and capi v1alpha4 and got the same issue https://jenkins.nordix.org/view/Airship/job/airship_master_feature_tests_upgrade_ubuntu/435/console

**Comment by furkatgofurov7** [comment]
Please do not trigger feature tests until it is fixed, otherwise it is just a waste of resources in CI.

**Review by namnx228 — APPROVED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
