### PR TITLE
Revert "Make upgrade test CAPI v1a4 -> v1b1"

### PR DESCRIPTION
**Pull request by lentzi90**
This reverts commit a013d4e3776743616c04bf1994e507f213f2881f.

Just to test if this fixes the upgrade test.

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
Checked the master job and it is still failing, maybe we should take this in for now and work on the fix on the follow-up.

/approve

**Comment by lentzi90** [comment]
/hold
Please see this gerrit change instead: https://gerrit.nordix.org/c/infra/cicd/+/12001
It will hopefully solve the issue.

**Comment by lentzi90** [comment]
Closing as the gerrit change linked above fixed the issue.

**Pull request closed without merging**
