### PR TITLE
uplift KUBERNETES_VERSION to v1.23.3

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplift KUBERNETES_VERSION to v1.23.2

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
@Sunnatillo since 1.23.3 is out meanwhile, lets uplift to that, for feature/upgrade we can take source to 1.23.2 and then go to 1.23.3.

**Comment by furkatgofurov7** [comment]
@Sunnatillo Images are not there yet for `v1.23.3`, let's for image builds to finish first.

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Pull request merged**
