### PR TITLE
Enable authentication in sushy-tools

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by dtantsur** [comment]
Docker rate limit in the failed job, need to recheck tomorrow morning.

**Comment by fmuyassarov** [comment]
> Docker rate limit in the failed job, need to recheck tomorrow morning.

yes, sorry for that. We trying to fix it.

**Comment by fmuyassarov** [comment]
@dtantsur we haven't yet fixed docker issue. So, it might fail again for centos v1a4

**Review by elfosardo — APPROVED** [review]

**Comment by dtantsur** [comment]
Yay, it passed, thank you!

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
