### PR TITLE
WIP: Updates needed while testing with zuul

### PR DESCRIPTION
**Pull request by pabelanger**
Also enable debug for bash commands.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by nordixinfra** [comment]
Can one of the admins verify this patch?

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now d2171f6eec8c2fbb17a6eb2e5ecd1f326d0c7f88

**Comment by pabelanger** [comment]
please don't merge, testing with zuul

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now b4875b59a13bf56fac76c158eea0a9910faf8320

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now f9ee920461342020c32f589bf5de26bf1dee47c1

**Comment by russellb** [comment]
feel free to reopen this if / when needed!

**Pull request closed without merging**
