### PR TITLE
Test new node image built with DIB

### PR DESCRIPTION
**Pull request by NymanRobin**
This PR is mainly meant to test the new image built with Disk Image builder in this PR:
[#679](https://github.com/metal3-io/project-infra/pull/679)

### CODE REVIEW

**Comment by NymanRobin** [comment]
Thanks @Sunnatillo for running the tests, but seems like I missed this comment 
`# Kubectl version (do not forget to update KUBECTL_SHA256 when changing KUBERNETES_VERSION!)`

But maybe just hard coding the image directly would work, but I will check this in a bit more detail if you do not already know?

**Comment by Sunnatillo** [comment]
Lets run this on project infra and manually set all the vars there.

**Pull request closed without merging**
