### PR TITLE
Bump golang to v1.20.7

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
What now Prow... the test passed.
Let's try a 
/retest

**Comment by tuminoid** [comment]
The PR is not visible in Tide history at all. Let's include one prow based test, maybe it helps.
/test shellcheck

**Comment by lentzi90** [comment]
Oh well, the CAPM3 release for v1.5 is not out yet :disappointed:

**Comment by tuminoid** [comment]
> Oh well, the CAPM3 release for v1.5 is not out yet 😞

Do we want to just override 1.5 and get this moving, or wait?

**Comment by tuminoid** [comment]
/override test-centos-integration-release-1-5 

1.5 is not out, so need to skip this to get this merged and unblock the release activity.

**Pull request merged**
