### PR TITLE
🌱 bump k8s to v1.31.0

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
- bump k8s to v1.31.0
- KIND_VERSION to v0.23.0
- KIND_NODE_IMAGE_VERSION to v1.30.0

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
we don't have 1.31 image on artifactory yet that's why it's failing.

**Comment by tuminoid** [comment]
> we don't have 1.31 image on artifactory yet that's why it's failing.

Where does the image come from? Manual?

**Comment by adilGhaffarDev** [comment]
> Where does the image come from? Manual?

jenkins job should push it, but seems like it didn't work, @Sunnatillo has pushed them manually.

**Comment by Sunnatillo** [comment]
Can you update renovate.json as well like in here?
https://github.com/Nordix/metal3-dev-env/commit/f7c2c40dff51c6076e66a2023e8b0e57e9dcbb1b#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57

Lets wait for the tests to pass before doing the change. We can just override them.

**Comment by adilGhaffarDev** [comment]
> Can you update renovate.json as well like in here?
> [Nordix@f7c2c40#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57](https://github.com/Nordix/metal3-dev-env/commit/f7c2c40dff51c6076e66a2023e8b0e57e9dcbb1b#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57)

done

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-release-1-7
/override metal3-dev-env-integration-test-ubuntu-main

Per comment above, only renovate was changed after tests had passed.

**Pull request merged**
