### PR TITLE
Bump the Golang version to 1.16

### PR DESCRIPTION
**Pull request by fmuyassarov**
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)

### CODE REVIEW

**Comment by kashifest** [comment]
lgtm
/test-centos-integration
/test-integration

**Comment by kashifest** [comment]
Do we need to run v1a3 ?? Nope I guess

**Comment by fmuyassarov** [comment]
> Do we need to run v1a3 ?? Nope I guess

Not sure :)

**Comment by fmuyassarov** [comment]
/hold 
@kashifest if you think we need to run v1a3 too, please let me know, otherwise we can remove the hold

**Comment by kashifest** [comment]
> /hold
> @kashifest if you think we need to run v1a3 too, please let me know, otherwise we can remove the hold

IMO no, sorry for raising doubt in the first place

**Comment by fmuyassarov** [comment]
> IMO no, sorry for raising doubt in the first place

no problem :)

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
